### ISSUE TITLE
Try Make.sh

### ISSUE THREAD

**Issue by AceKevinMark** [mengzhuo/gontpd#2]
./make.sh: line 15: fpm: command not found

**Comment by mengzhuo** [comment]
You need https://github.com/jordansissel/fpm

**Comment by AceKevinMark** [comment]
from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/leanote/gopackage/bin/fpm:4:in `<main>'

**Comment by mengzhuo** [comment]
It's beyond this project, please report to the fpm project.
